### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

### ISSUE THREAD

**Issue by percentile** [lukaszbanasiak/yahoo-finance#116]
I am trying to use yahoo-finance for the first time on a mac.  When I call

share = Share('YHOO')

python errors with a long string of line references ending in:

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

Investigating, I thought this may have to do with an older version of openssl, but I upgraded, relinked it (tough to do on a Mac) and verified that Python is using the latest:

bash-3.2$ python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.2h  3 May 2016'

any clues to what is wrong or how to fix it?

**Comment by percentile** [comment]
never mine, just solved it myself with instructions from:

http://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by fschr** [comment]
@percentile nice work. Can you close the issue?

**Comment by percentile** [comment]
What I did above solved the issue when I run within Eclipse but mysteriously, I am getting the same issue when I run my scripts at the command line:

Traceback (most recent call last):
  File "DQuotes.py", line 90, in <module>
    dq.yahoo_financials()
  File "DQuotes.py", line 68, in yahoo_financials
    share = Share('YHOO')      
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

I think this has to do with whatever strange mechanics are going on with SSL for Python on the Mac, but I will leave this open in case anyone else has any ideas on how to make this work.  All I can find on a number of StackOverflow threads is to perform the steps above or to upgrade the certifi module which I have done.

**Comment by fschr** [comment]
@percentile This is probably due to the fact that you have multiple Python distributions installed and the one you're running in Eclipse is not the same one that you're running on the command line.
