### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by gurnit1** [lukaszbanasiak/yahoo-finance#13]
I was able to run simple commands yesterday but am not able to run them today. I ran the follow line in Python Shell:
stock = Share('YHOO')

and got the following error:

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    stock = Share('YHOO')
  File "C:\Python27\lib\site-packages\yahoo_finance\__init__.py", line 176, in __init__
    self.refresh()
  File "C:\Python27\lib\site-packages\yahoo_finance\__init__.py", line 140, in refresh
    self.data_set = self._fetch()
  File "C:\Python27\lib\site-packages\yahoo_finance\__init__.py", line 179, in _fetch
    data = super(Share, self)._fetch()
  File "C:\Python27\lib\site-packages\yahoo_finance\__init__.py", line 132, in _fetch
    data = self._request(query)
  File "C:\Python27\lib\site-packages\yahoo_finance\__init__.py", line 116, in _request
    response = yql.YQLQuery().execute(query)
  File "C:\Python27\lib\site-packages\yahoo_finance\yql.py", line 51, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "C:\Python27\lib\httplib.py", line 1074, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Its happening for any ticker symbol I provide

**Comment by lukaszbanasiak** [comment]
Strange, works for me. Maybe you have a problem with network? You have the opportunity to test this on different network?

    >>> yahoo.get_price()
    '43.99'
    >>> yahoo.get_trade_datetime()
    '2015-03-04 21:00:00 UTC+0000'
