### ISSUE TITLE
Historical Data broken?

### ISSUE THREAD

**Issue by gpaw789** [lukaszbanasiak/yahoo-finance#135]
Looks like Yahoo shut down "unsupported API"
https://forums.yahoo.net/t5/Yahoo-Finance-help/has-yahoo-stopped-history-data-api-service/td-p/231325

**Comment by gpaw789** [comment]
Hi I hope you guys don't mind, I forked the project and added get_historical2(), it will produce the exact same output as get_historical() but a bit slower (okay I lie its a lot slower)

https://github.com/gpaw789/yahoo-finance

**Comment by iamlxb3** [comment]
when using your get_his2, something happened...

```
Retrying to get cookie.... 2 retries left
Traceback (most recent call last):
  File "download_dow_jones_extended_data.py", line 3, in <module>
    yahoo.get_historical2('2014-04-25', '2014-05-29')
  File "F:\ProgramData\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", l
ine 358, in get_historical2
    hist = gp.get_hist(self.symbol, start_date, end_date)
  File "F:\ProgramData\Anaconda3\lib\site-packages\yahoo_finance\gp.py", line 10
3, in get_hist
    cookie, crumb = get_cookie_crumb(symbol)
  File "F:\ProgramData\Anaconda3\lib\site-packages\yahoo_finance\gp.py", line 51
, in get_cookie_crumb
    cookie, lines = get_page_data(symbol)
  File "F:\ProgramData\Anaconda3\lib\site-packages\yahoo_finance\gp.py", line 44
, in get_page_data
    cookie = get_cookie_value(r)
  File "F:\ProgramData\Anaconda3\lib\site-packages\yahoo_finance\gp.py", line 38
, in get_cookie_value
    return {'B': r.cookies['B']}
  File "F:\ProgramData\Anaconda3\lib\site-packages\requests\cookies.py", line 32
7, in __getitem__
    return self._find_no_duplicates(name)
  File "F:\ProgramData\Anaconda3\lib\site-packages\requests\cookies.py", line 39
8, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='B', domain=None, path=None"
```

**Comment by gpaw789** [comment]
Hi mate, I just ran mine it works fine for TSLA symbol.
Can you reinstall your requests module?

This is my output:
---------------------------------------------
Python 3.6.1 (default, Apr  4 2017, 09:36:47) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> symbol = Share("TSLA")
>>> symbol.get_price()
'339.60'
>>> get_historical2("2017-06-28", "2017-07-25")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_historical2' is not defined
>>> symbol.get_historical2("2017-06-28", "2017-07-25")
[{'Date': '2017-06-28', 'Open': '366.679993', 'High': '371.739990', 'Low': '362.519989', 'Close': '371.239990', 'Adj_Close': '371.239990', 'Volume': '6302500', 'Symbol': 'TSLA'}, {'Date': '2017-06-29', 'Open': '370.609985', 'High': '371.000000', 'Low': '354.100006', 'Close': '360.750000', 'Adj_Close': '360.750000', 'Volume': '8221000', 'Symbol': 'TSLA'}, {'Date': '2017-06-30', 'Open': '363.709991', 'High': '366.769989', 'Low': '359.619995', 'Close': '361.609985', 'Adj_Close': '361.609985', 'Volume': '5828300', 'Symbol': 'TSLA'}, {'Date': '2017-07-03', 'Open': '370.239990', 'High': '371.350006', 'Low': '351.500000', 'Close': '352.619995', 'Adj_Close': '352.619995', 'Volume': '6305400', 'Symbol': 'TSLA'}, {'Date': '2017-07-05', 'Open': '347.200012', 'High': '347.239990', 'Low': '326.329987', 'Close': '327.089996', 'Adj_Close': '327.089996', 'Volume': '17046700', 'Symbol': 'TSLA'}, {'Date': '2017-07-06', 'Open': '317.260010', 'High': '320.790009', 'Low': '306.299988', 'Close': '308.829987', 'Adj_Close': '308.829987', 'Volume': '19324500', 'Symbol': 'TSLA'}, {'Date': '2017-07-07', 'Open': '313.500000', 'High': '317.000000', 'Low': '307.380005', 'Close': '313.220001', 'Adj_Close': '313.220001', 'Volume': '14176900', 'Symbol': 'TSLA'}, {'Date': '2017-07-10', 'Open': '312.899994', 'High': '317.940002', 'Low': '303.130005', 'Close': '316.049988', 'Adj_Close': '316.049988', 'Volume': '13820900', 'Symbol': 'TSLA'}, {'Date': '2017-07-11', 'Open': '316.000000', 'High': '327.279999', 'Low': '314.299988', 'Close': '327.220001', 'Adj_Close': '327.220001', 'Volume': '11559400', 'Symbol': 'TSLA'}, {'Date': '2017-07-12', 'Open': '330.399994', 'High': '333.100006', 'Low': '324.500000', 'Close': '329.519989', 'Adj_Close': '329.519989', 'Volume': '10346100', 'Symbol': 'TSLA'}, {'Date': '2017-07-13', 'Open': '330.109985', 'High': '331.600006', 'Low': '319.970001', 'Close': '323.410004', 'Adj_Close': '323.410004', 'Volume': '8594500', 'Symbol': 'TSLA'}, {'Date': '2017-07-14', 'Open': '323.190002', 'High': '328.420013', 'Low': '321.220001', 'Close': '327.779999', 'Adj_Close': '327.779999', 'Volume': '5625200', 'Symbol': 'TSLA'}, {'Date': '2017-07-17', 'Open': '325.540009', 'High': '327.100006', 'Low': '313.450012', 'Close': '319.570007', 'Adj_Close': '319.570007', 'Volume': '9876900', 'Symbol': 'TSLA'}, {'Date': '2017-07-18', 'Open': '317.500000', 'High': '329.130005', 'Low': '315.660004', 'Close': '328.239990', 'Adj_Close': '328.239990', 'Volume': '6373700', 'Symbol': 'TSLA'}, {'Date': '2017-07-19', 'Open': '328.230011', 'High': '331.649994', 'Low': '323.220001', 'Close': '325.260010', 'Adj_Close': '325.260010', 'Volume': '6357000', 'Symbol': 'TSLA'}, {'Date': '2017-07-20', 'Open': '326.899994', 'High': '330.220001', 'Low': '324.200012', 'Close': '329.920013', 'Adj_Close': '329.920013', 'Volume': '5166200', 'Symbol': 'TSLA'}, {'Date': '2017-07-21', 'Open': '329.459991', 'High': '331.260010', 'Low': '325.799988', 'Close': '328.399994', 'Adj_Close': '328.399994', 'Volume': '4901600', 'Symbol': 'TSLA'}, {'Date': '2017-07-24', 'Open': '330.239990', 'High': '343.399994', 'Low': '330.010010', 'Close': '342.519989', 'Adj_Close': '342.519989', 'Volume': '8637100', 'Symbol': 'TSLA'}, {'Date': '2017-07-25', 'Open': '345.000000', 'High': '345.600006', 'Low': '334.149994', 'Close': '339.600006', 'Adj_Close': '339.600006', 'Volume': '6971900', 'Symbol': 'TSLA'}]
