### ISSUE TITLE
get_historical() doesn't work any more - throws an exception

### ISSUE THREAD

**Issue by vivekcmenon** [lukaszbanasiak/yahoo-finance#138]
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> yahoo.Share("MSFT")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'yahoo' is not defined
>>> yahoo = Share("MSFT")
>>> yahoo.get_price()
'72.68'
>>> yahoo.get_historical("2017-08-01", "2017-08-02")
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)
  File "/usr/local/lib/python3.5/dist-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

**Comment by nilesr** [comment]
Observing the same thing over here

**Comment by vivekcmenon** [comment]
From some browsing it seems like yahoo changed their api and there is a fix for historical quotes at the following link. Did a basic test and it worked.

**Comment by AndrewRPorter** [comment]
https://github.com/AndrewRPorter/yahoo-historical

**Comment by pmatos** [comment]
@vivekcmenon unfortunately `fix_yahoo_finance` has quite a few issues with regards to returning complete data. Sometimes incomplete data is shown. See ranaroussi/fix-yahoo-finance#22.

**Comment by DennyWeinberg** [comment]
+1

**Comment by knair99** [comment]
Here's a workaround (grab the data directly from the history pages):

```
import urllib2
from BeautifulSoup import BeautifulSoup as bs

def get_historical_data(name, number_of_days):
	data = []
	url = "https://finance.yahoo.com/quote/" + name + "/history/"
	rows = bs(urllib2.urlopen(url).read()).findAll('table')[0].tbody.findAll('tr')

	for each_row in rows:
		divs = each_row.findAll('td')
		if divs[1].span.text  != 'Dividend': #Ignore this row in the table
			#I'm only interested in 'Open' price; For other values, play with divs[1 - 5]
			data.append({'Date': divs[0].span.text, 'Open': float(divs[1].span.text.replace(',',''))})

	return data[:number_of_days]

#Test
print get_historical_data('amzn', 15)
```
