### ISSUE TITLE
'module' object has no attribute '_strptime'

### ISSUE THREAD

**Issue by hockeymikey** [lukaszbanasiak/yahoo-finance#14]
Getting the following error when trying to grab a price of a stock using 

price = Share(symbol).get_price()

I'm testing this on a Windows 7 machine.

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in **bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "C:/Users/Mikey Hajostek/Desktop/pyvse/BenBot.py", line 220, in get_quote
    price = Share(symbol).get_price()
  File "C:\Python27\lib\site-packages\yahoo_finance__init**.py", line 176, in **init**
    self.refresh()
  File "C:\Python27\lib\site-packages\yahoo_finance__init__.py", line 140, in refresh
    self.data_set = self._fetch()
  File "C:\Python27\lib\site-packages\yahoo_finance__init__.py", line 181, in _fetch
    data[u'LastTradeDateTimeUTC'] = edt_to_utc('{0} {1}'.format(data['LastTradeDate'], data['LastTradeTime']))
  File "C:\Python27\lib\site-packages\yahoo_finance__init__.py", line 21, in edt_to_utc
    date_ = datetime.strptime(date, mask)
AttributeError: 'module' object has no attribute '_strptime'

**Comment by lukaszbanasiak** [comment]
@hockeymikey if this still valid feel free to reopen issue
