### ISSUE TITLE
Stopped working from 11/01/2017

### ISSUE THREAD

**Issue by wyyang** [lukaszbanasiak/yahoo-finance#140]
```
>>> from yahoo_finance import Share
>>> aapl = Share('AAPL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/weiyi_yang/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Users/weiyi_yang/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Users/weiyi_yang/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Users/weiyi_yang/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Users/weiyi_yang/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.
```

**Comment by MikeRixWolfe** [comment]
The text on the page has been updated to say:

"It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com."

Looks like the party's over?

**Comment by karen-ho** [comment]
One of the administrators has been asking people to reply in the Yahoo Finance Feedback Forum: https://yahoo.uservoice.com/forums/382977 I'm hoping if this issue gets enough votes and feedback that they will reconsider discontinuing this service: https://yahoo.uservoice.com/forums/382977-finance/suggestions/32117227-yahoo-support-i-have-used-the-http-code-below-fo#comments

**Comment by drandreaskrueger** [comment]
What a f**kup. Yahoo as a whole should be discontinued. 

Now I understand why suddenly my [btc.hopto.org](http://btc.hopto.org) stopped working completely.

So ... looks like we must be moving to [googlefinance.client](https://pypi.python.org/pypi/googlefinance.client) now

**Comment by drandreaskrueger** [comment]
> to googlefinance.client now

but that is stupidly heavy, it includes pandas.

Anyone with a third idea?

Thanks.

**Comment by drandreaskrueger** [comment]
And sorry that your whole beautiful repo is dead now, what a disgrace. 

Watch: 68  Star: 581  Fork: 231

Kudos.

And: My condolences.

**Comment by likewhoa** [comment]
R.I.P

**Comment by muzhig** [comment]
Maybe this can help, seems working for me:

`def get_yahoo_finance_data(symbol, start=None, end=None, interval='1m'):
    end = end or datetime.datetime.utcnow()
    start = start or end - datetime.timedelta(hours=24)
    url = 'https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?symbol={symbol}&period1={start}&period2={end}&interval={interval}&includePrePost=true&events=div%7Csplit%7Cearn&corsDomain=finance.yahoo.com'.format(
        symbol=symbol,
        start=start.strftime('%s'),
        end=end.strftime('%s'),
        interval=interval
    )
    resp = requests.get(url)
    resp.raise_for_status()
    return resp.json()`

**Comment by KurtPrice** [comment]
Have we considered parsing the data our self by forming urls for the webpages that contain our ticker mark and parsing for the price data?

**Comment by muzhig** [comment]
Here is routine for downloading historical data (python3):
```def download_daily_ohlc(symbol, start, end):
    ses = requests.session()
    resp = ses.get(
        f'https://finance.yahoo.com/quote/{symbol}/history?period1={start}&period2={end}&interval=1d&filter=history&frequency=1d'
    )
    resp.raise_for_status()
    data = resp.content.decode('utf-8')
    crumb_m = re.search(r'"CrumbStore":\{"crumb":("[^"]+")\}', data)
    assert crumb_m
    crumb = json.loads(crumb_m.group(1))
    csvresp = ses.get(
        f'https://query1.finance.yahoo.com/v7/finance/download/{symbol}?period1={start}&period2={end}&interval=1d&events=history&crumb={crumb}'
    )
    try:
        csvresp.raise_for_status()
    except Exception as ex:
        print(ex)
        raise
    return csvresp.content
```

**Comment by addisonlynch** [comment]
Would recommend IEX as an alternative. Mostly the same functionality. [This Python wrapper](http://github.com/addisonlynch/iexfinance) should work.

**Comment by shaad1994** [comment]
when i tried to open jupyter notebook this is happened ..pls someone help to fix this problem..



Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Dell>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Dell\Anaconda2\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Dell\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\Dell\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\tcpserver.py", line 143, in listen
    self.add_sockets(sockets)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\tcpserver.py", line 155, in add_sockets
    self.io_loop = IOLoop.current()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 214, in current
    return IOLoop.instance()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 162, in instance
    IOLoop._instance = IOLoop()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\util.py", line 293, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 709, in initialize
    self._waker = Waker()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\platform\common.py", line 64, in __init__
    self.writer.connect(connect_address)
  File "C:\Users\Dell\Anaconda2\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

C:\Users\Dell>

**Comment by MikeRixWolfe** [comment]
@shaad1994 this package doesn't work anymore, mate

**Comment by rickyhan** [comment]
Please archive this repo to avoid further confusion! @lukaszbanasiak

**Comment by addisonlynch** [comment]
+1

**Comment by JECSand** [comment]
Hey all, 

If you are needing an easy to setup module that returns free financial data from Yahoo, why not give my module a try:

https://github.com/JECSand/yahoofinancials

$ pip install yahoofinancials

YF can get most of the data yahoo-finance could. There are a few indexes however that aren't returning historical stock price data such as FTSE. However, that data is available on the interactive stock chart. I just haven't found an easy way to scrap it yet. Would love to hear any ideas anyone has. That's pretty much the last piece of the puzzle for YahooFinancials to reach v1.0.

https://finance.yahoo.com/chart/%5EFTSE

Hope this helps!
