### ISSUE TITLE
Basic functionality not working

### ISSUE THREAD

**Issue by ambarish710** [lukaszbanasiak/yahoo-finance#148]
Code snippet -
```
from yahoo_finance import Share
yahoo = Share('YHOO')
print(yahoo.get_open())
```

I see the following error,
```
python hist_stock.py 
Traceback (most recent call last):
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hist_stock.py", line 3, in <module>
    yahoo = Share('YHOO')
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/Users/Ambarish/.pyenv/versions/stock-test/lib/python3.7/site-packages/yahoo_finance/yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/Ambarish/.pyenv/versions/3.7.7/lib/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

Python and PIP packages present --
```
(stock-test) Ambarishs-MacBook-Pro:tmp Ambarish$ python -V
Python 3.7.7
(stock-test) Ambarishs-MacBook-Pro:tmp Ambarish$ pip list
Package       Version
------------- -------
pip           20.1.1
pytz          2020.1
setuptools    41.2.0
simplejson    3.17.0
yahoo-finance 1.4.0
```

Is there any specific URL lib version that I need to download?

**Comment by kevinpthorne** [comment]
> Yahoo! Finance backend is http://datatables.org/. If this service is down or has network problems you will receive errors from group YQL*, eg. YQLQueryError.

>You can monitor this service via https://www.datatables.org/healthchecker/

The DataTables website doesn't even load for me. That could be the issue.

**Comment by laktej** [comment]
This link is not accessible 
https://www.datatables.org/healthchecker/

**Comment by yogeshnile** [comment]
Code:- 
```python
from yahoo_finance import Share
yahoo = Share('YHOO')
print(yahoo.get_open())
```

Error Occur:-
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    yahoo = Share('YHOO')
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/home/yogesh/.local/lib/python3.6/site-packages/yahoo_finance/yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>```

**Comment by ReihanHaekal** [comment]
I have the same problem here. and datatable site won't load anymore. any suggestion where I can get similar functionality with this repos. I need a live market share price for my country, Indonesia.

**Comment by FrankDMartinez** [comment]
Same issue here. Any suggestions? Anyone monitoring this issue? Is this project abandoned?

**Comment by Zhanibek6** [comment]
https://stackoverflow.com/questions/44050518/is-yql-datatables-org-down-as-of-may-17-18-2017

Yahoo has officially confirmed that the Yahoo Finance API has been discontinued.

**Comment by FrankDMartinez** [comment]
@Zhanibek6 Discontinuation of the API is one thing, though experience shows the API is still available. I think the open question is on the deprecation message from inside this particular library.

**Comment by zurachf** [comment]
> I have the same problem here. and datatable site won't load anymore. any suggestion where I can get similar functionality with this repos. I need a live market share price for my country, Indonesia.

have you found any useful API instead?

**Comment by Zhanibek6** [comment]
There is a yfinance.

**Comment by johnny345** [comment]
That particular ticker YHOO, has been gone for years.  Not really understanding how this was updated a couple of months ago, when the API has been gone for years.  Is this a virus/spyware?
