### ISSUE TITLE
Error retrieving quotes for symbols with special characters

### ISSUE THREAD

**Issue by nisargshah95** [lukaszbanasiak/yahoo-finance#22]
If I try to obtain quotes for companies which have a '&' in their symbol, for eg., "J&KBANK.BO", I get the following stack trace -
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print Share("J&KBANK.BO")
  File "/usr/local/lib/python2.7/dist-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/local/lib/python2.7/dist-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/usr/local/lib/python2.7/dist-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/local/lib/python2.7/dist-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'
```
Is there a workaround?

**Comment by josuebrunel** [comment]
Hello @nisargshah95,
I tried to debug the lib and this a lil traceback 
* The query is well formatted -> [source code](https://github.com/lukaszbanasiak/yahoo-finance/blob/master/yahoo_finance/__init__.py#L85)
```python
(pdb) print query
'select * from yahoo.finance.quotes where symbol = "J&KBANK.BO"'
```
* The response is NULL -> [source code](https://github.com/lukaszbanasiak/yahoo-finance/blob/master/yahoo_finance/__init__.py#L118)
```python
(pdb) response
{'query': {'count': 0, 'lang': 'en-US', 'results': None, 'created': '2015-06-30T11:05:54Z'}}
```

* Where does it hurt then ?

No where actually, check [these lines](https://github.com/lukaszbanasiak/yahoo-finance/blob/master/yahoo_finance/__init__.py#L122-125) though
```python
(pdb) AttributeError: "'NoneType' object has no attribute 'popitem'"
```
Because ***response['query']['result']*** is **None**

[This statement](https://github.com/lukaszbanasiak/yahoo-finance/blob/master/yahoo_finance/__init__.py#L123) seems to be line where things go south
```python
(Pdb) response['error']['description'] 
```
For a reason i haven't found yet, it doesn't got into the **except** then the **else**.

It's definitely not the **your symbol** at all. I will keep you posted if i sort it out ( if i ever have time ).
