### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by kvdveer** [lukaszbanasiak/yahoo-finance#44]
It seems that the backing API has been taken offline, sadly.

```python
from yahoo_finance import Share
yahoo = Share('YHOO')
```

Ouputs
```
YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
```

**Comment by alons45** [comment]
![test](https://cloud.githubusercontent.com/assets/1877511/13607752/980dd728-e51f-11e5-88c0-66620b69c123.png) Work for me

**Comment by BenBrostoff** [comment]
@kvdveer Any luck on this one? I have a cron task that has used this library for a few months and it failed with this error for the first time today.

**Comment by rkhwaja** [comment]
You could switch to http://finance.yahoo.com/webservice/v1/symbols/YHOO,AAPL/quote?format=json&view=detail
That one still works

**Comment by relima** [comment]
I am also having problems with stocks and exchange quotes.

**Comment by drewall3000** [comment]
It's working again

**Comment by drewall3000** [comment]
It works off and on it seems.  I just keep compiling until it works for the time being

**Comment by tbenst** [comment]
Not working for me

**Comment by alons45** [comment]
Now same :( not working for me, random bug?

**Comment by mixographer** [comment]
Stopped again today:

>>> a = Share('YHOO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/yahoo_finance/__init__.py", line 178, in __init__
  File "build/bdist.macosx-10.11-intel/egg/yahoo_finance/__init__.py", line 142, in refresh
  File "build/bdist.macosx-10.11-intel/egg/yahoo_finance/__init__.py", line 181, in _fetch
  File "build/bdist.macosx-10.11-intel/egg/yahoo_finance/__init__.py", line 134, in _fetch
  File "build/bdist.macosx-10.11-intel/egg/yahoo_finance/__init__.py", line 123, in _request
yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".

**Comment by jwallden** [comment]
Working for me

**Comment by lukaszbanasiak** [comment]
Errors from group `YQL*` like `YQLQueryError` are trow when Yahoo endpoint returns error.
Basically `YQLQueryError` is used to translate endpoint errors to Python exceptions.

Example of error retrieved from Yahoo endpoint:
`"ErrorIndicationreturnedforsymbolchangedinvalid": "No such ticker symbol. (...)",`

If bug not longer occurs I will close this issue.
Please do not hesitate to open new issue if any similar bug occurs in feature.

**Comment by alons45** [comment]
![erroryahoo](https://cloud.githubusercontent.com/assets/1877511/19202371/8816db74-8c97-11e6-80a7-8d8935f8a319.png)

Same error again

**Comment by endir** [comment]
Same problem again! :(

**Comment by endir** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/a.py", line 4, in <module>
    gbp_eur = yahoo_finance.Currency('GBPEUR')
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.xchange'".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/a.py", line 6, in <module>
    gbp_eur = yahoo_finance.Currency('GBPEUR')
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
yahoo_finance.YQLQueryError: Query failed with error: "'No definition

**Comment by endir** [comment]
In python 2:

raceback (most recent call last):
  File "/tmp/a.py", line 6, in <module>
    gbp_eur = yahoo_finance.Currency('GBPEUR')
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.xchange'".

**Comment by alanyhyu** [comment]
Sorry but the error is back.

![yahoostockmoduleerror](https://cloud.githubusercontent.com/assets/18442168/19281033/380a7178-8fb6-11e6-8751-9f873e311ac2.jpg)


---------------------------------------------------------------------------
YQLQueryError                             Traceback (most recent call last)
<ipython-input-10-56b0fba5a8f2> in <module>()
      1 from yahoo_finance import *
      2 
----> 3 yahoo = Share('YHOO')
      4 yahoo.get_price()

//anaconda/lib/python2.7/site-packages/yahoo_finance/__init__.pyc in __init__(self, symbol)
    176         self._table = 'quotes'
    177         self._key = 'symbol'
--> 178         self.refresh()
    179 
    180     def _fetch(self):

//anaconda/lib/python2.7/site-packages/yahoo_finance/__init__.pyc in refresh(self)
    140 
    141         """
--> 142         self.data_set = self._fetch()
    143 
    144 

//anaconda/lib/python2.7/site-packages/yahoo_finance/__init__.pyc in _fetch(self)
    179 
    180     def _fetch(self):
--> 181         data = super(Share, self)._fetch()
    182         if data['LastTradeDate'] and data['LastTradeTime']:
    183             data[u'LastTradeDateTimeUTC'] = edt_to_utc('{0} {1}'.format(data['LastTradeDate'], data['LastTradeTime']))

//anaconda/lib/python2.7/site-packages/yahoo_finance/__init__.pyc in _fetch(self)
    132     def _fetch(self):
    133         query = self._prepare_query(table=self._table, key=self._key)
--> 134         data = self._request(query)
    135         return data
    136 

//anaconda/lib/python2.7/site-packages/yahoo_finance/__init__.pyc in _request(self, query)
    121         except (KeyError, StopIteration):
    122             try:
--> 123                 raise YQLQueryError(response['error']['description'])
    124             except KeyError:
    125                 raise YQLResponseMalformedError()

YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".

**Comment by maciz84** [comment]
This is really frustrating, I am experiencing this today? Any update from anybody?

**Comment by lukaszbanasiak** [comment]
@maciz84 look at my comment above https://github.com/lukaszbanasiak/yahoo-finance/issues/44#issuecomment-241658859
It's online service powered by Yahoo not creator of library :)

**Comment by sresam89** [comment]
`You could switch to http://finance.yahoo.com/webservice/v1/symbols/YHOO,AAPL/quote?format=json&view=detail
That one still works'

Does not work

**Comment by fschvart** [comment]
Hi quick question, is there any way I could, using the API, get the historical data of multiple symbols?
I'm trying to get the data from the entire SP 500 portfolio and it takes like 10 minutes.
Thanks!

**Comment by hubofjon** [comment]
Hi, wondering if anyone can help me out. I began to get below alert since Monday.
URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

Thanks in advance

**Comment by justus0me** [comment]
Hey,
is there an option to pull up the dividends in the Historical data?
I didn't see it in the documentation.

**Comment by andoresu47** [comment]
Seems to be dead again...I get HTTP Error 500: Server Error randomly

**Comment by pratibhajagnere** [comment]
In Python 3.4.3, below error occur. It seems[ YQL console](https://developer.yahoo.com/yql/console/) is down.

Traceback (most recent call last):
 File "YahooFinance.py", line 51, in <module>
 File "YahooFinance.py", line 13, in get_YFData
 File "C:\Python34\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
   self.refresh()
 File "C:\Python34\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
   self.data_set = self._fetch()
 File "C:\Python34\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
   data = super(Share, self)._fetch()
 File "C:\Python34\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
   data = self._request(query)
 File "C:\Python34\lib\site-packages\yahoo_finance\__init__.py", line 125, in _request
   raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed..

**Comment by idanb1** [comment]
Hey, I need to check all symbols of yahoo finance, and get those who up more than 1%.
There is any function with 'yahoo-finance' that I can scan all symbols?
Best regards,
Idan.

**Comment by RedEyeDragon** [comment]
The method get_price() is not returing the correct price. Also get_open() is either returning "None" or an incorrect value as well. Is the http header link broken or has Yahoo completely stoped allowing this?

**Comment by muaazsalagar** [comment]
@red] @andoresu47  Hello guys can you please tell me, if this API is working for you? specifically for historical prices?

**Comment by ptrvw** [comment]
Hello

I get a bad request on Share since some time. Was working perfectly before and i didnt change a thing. Its yahoo-finance 1.4.0. Below a dump from the python prompt on my macbookpro:
>>> from yahoo_finance import Share
>>> yahoo = Share('YHOO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/Library/Python/2.7/site-packages/yahoo_finance/yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

Any thoughts?
Pieter.

**Comment by simonagallagher** [comment]
Hello,

I have the exact same problem as Peter. It's been working no problem for a long time, and for a week or two there's some sort of problem. I didn't change my code at all...

Here's a dump from the console:

```
runfile('C:/Users/simongallagher/Desktop/Python Stock/Stock_Program_debug.py', wdir='C:/Users/simongallagher/Desktop/Python Stock')
Traceback (most recent call last):
  File "<ipython-input-1-fbc79b24c9f7>", line 1, in <module>
    runfile('C:/Users/simongallagher/Desktop/Python Stock/Stock_Program_debug.py', wdir='C:/Users/simongallagher/Desktop/Python Stock')
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/simongallagher/Desktop/Python Stock/Stock_Program_debug.py", line 30, in <module>
    tic = Share(ticker)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
    self.refresh()
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
    data = self._request(query)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\site-packages\yahoo_finance\yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\simongallagher\AppData\Local\Continuum\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
HTTPError: Bad Request
```

Does anyone have any ideas?
Thanks!
Simon

**Comment by JulianStorz** [comment]
Since maybe two or three days, I do get this Error message when using Share("TICKER_NAME"):

```
Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Julian\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-137-b39db1fe6afa>", line 1, in <module>
    apple = Stock_Analysis("AAPL","2015-01-01")
  File "<ipython-input-136-1d74432311a1>", line 6, in __init__
    self.share = Share(self.ticker)
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
    self.refresh()
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
    data = self._request(query)
  File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.
```

Is this a known problem? Saw that there was a discussion about the console YQL being down. But there was no real answer/solution to the issue.
It is new to me as I used the yahoo_finance for my scripts since maybe half a year now.
Do you have any idea what causes this problem and how to solve it?

Thank you
~Best
Julian

**Comment by MiniXC** [comment]
https://www.datatables.org seems to be down.

**Comment by JulianStorz** [comment]
Still have the same issue - anyone has an idea of how to work around this issue?

**Comment by ptrvw** [comment]
get Response malformed on instantiating a Share (see below). Related to datatables being stil being  'down'?

>>> from yahoo_finance import Share
>>> yahoo = Share('YHOO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

**Comment by LyaSolis** [comment]
@ptrvw   have you had any luck? I got the same error

**Comment by MirageL** [comment]
@ptrvw @LyaSolis Same, have  you been able to find a fix?

**Comment by ptrvw** [comment]
i'm moving to another library :-)
https://www.datacamp.com/community/tutorials/finance-python-trading

**Comment by RedEyeDragon** [comment]
Does this new library support the cookie requirement? I am pretty upset that Yahoo stopped supporting their old API link because I developed an entire API using it then one day they just dropped it. Thanks for the link
Bryan Duarte | software engineer

ASU Computer Science Ph.D Student
IGERT Fellow
Alliance for Person-centered Accessible Technology (APAcT)
Center for Cognitive Ubiquitous Computing (CUbiC Lab)
National Federation of the Blind of Arizona | Affiliate Board Member
National Association of Blind Students | Board Member
Arizona Association of Blind Students | President
Phone: 480-652-3045

**Comment by llucax** [comment]
Also hitting the `AttributeError: 'NoneType' object has no attribute 'popitem'` error. Is this project abandoned?

**Comment by wjbaibai** [comment]
just test Share('YAHO')

it doesn't seem to work, anyone could help me?

Traceback (most recent call last):
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1406, in connect
    super().connect()
  File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\wjbai\Miniconda3\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\wjbai\Miniconda3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/wjbai/PycharmProjects/usstocks/test.py", line 5, in <module>
    yahoo = Share('YHOO')
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
    self.refresh()
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
    data = self._request(query)
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\yql.py", line 61, in execute
    'env': DATATABLES_URL
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by ma1onso** [comment]
> just test Share('YAHO')
> 
> it doesn't seem to work, anyone could help me?
> 
> Traceback (most recent call last):
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1317, in do_open
> encode_chunked=req.has_header('Transfer-encoding'))
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1244, in request
> self._send_request(method, url, body, headers, encode_chunked)
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1290, in _send_request
> self.endheaders(body, encode_chunked=encode_chunked)
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1239, in endheaders
> self._send_output(message_body, encode_chunked=encode_chunked)
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1026, in _send_output
> self.send(msg)
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 966, in send
> self.connect()
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 1406, in connect
> super().connect()
> File "C:\Users\wjbai\Miniconda3\lib\http\client.py", line 938, in connect
> (self.host,self.port), self.timeout, self.source_address)
> File "C:\Users\wjbai\Miniconda3\lib\socket.py", line 707, in create_connection
> for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> File "C:\Users\wjbai\Miniconda3\lib\socket.py", line 748, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 11001] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:/Users/wjbai/PycharmProjects/usstocks/test.py", line 5, in
> yahoo = Share('YHOO')
> File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance__init__.py", line 178, in **init**
> self.refresh()
> File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance__init__.py", line 142, in refresh
> self.data_set = self._fetch() File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance__init__.py", line 181, in _fetch
> data = super(Share, self)._fetch() File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance__init__.py", line 134, in _fetch
> data = self._request(query) File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance__init__.py", line 118, in _request
> response = yql.YQLQuery().execute(query)
> File "C:\Users\wjbai\Miniconda3\lib\site-packages\yahoo_finance\yql.py", line 61, in execute
> 'env': DATATABLES_URL
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 525, in open
> response = self._open(req, data)
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 543, in _open
> '_open', req)
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 503, in _call_chain
> result = func(*args)
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1360, in https_open
> context=self._context, check_hostname=self._check_hostname)
> File "C:\Users\wjbai\Miniconda3\lib\urllib\request.py", line 1319, in do_open
> raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Yahoo finance API was closed.

**Comment by markosole** [comment]
Did anyone get this working or there is another solution? Looks like those yahoo endpoints are not available any more.

**Comment by jwallden** [comment]
This project seems abandoned. I have moved to `yfinance` instead.(https://github.com/ranaroussi/yfinance) Works reasonably well although I just discovered some data that are not correct. Anyhow, check it out.

**Comment by markosole** [comment]
Thanks for updates. I have managed to build solution with sockets for NodeJS, which I use for live monitoring and alerts.
I will publish it soon to github, including Electron app and extra socket server.
