### ISSUE TITLE
Issue appeared today was working yesterday thanks in advance for creating though

### ISSUE THREAD

**Issue by drewall3000** [lukaszbanasiak/yahoo-finance#48]
>>> import yahoo_finance
>>> SPY = yahoo_finance.Share('SPY')
Traceback (most recent call last):
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/Users/andrewallin/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
>>>

**Comment by BenBrostoff** [comment]
FYI, [this is actually a repeat of this issue](https://github.com/lukaszbanasiak/yahoo-finance/issues/44).

**Comment by lukaszbanasiak** [comment]
@BenBrostoff thx for duplicate catch
