### ISSUE TITLE
Python 3.2.3: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by chris-h1** [lukaszbanasiak/yahoo-finance#62]
Could it be, that with python3.2 there is some error. Please see attached output.

```
python3.2
Python 3.2.3 (default, Feb 20 2013, 17:02:41)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/yahoo_finance/__init__.py", line 156
    data[u'DateTimeUTC'] = edt_to_utc('{0} {1}'.format(data['Date'], data['Time']))
                      ^
SyntaxError: invalid syntax
```

```
python
Python 2.7.3 (default, Jun 20 2016, 16:18:47)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> yahoo = Share('^TRJCRB')
>>> print (yahoo.get_price())
188.7796
>>>
```

```
python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26)
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> yahoo = Share('^TRJCRB')
>>> print (yahoo.get_price())
188.7796
>>>

```

**Comment by lukaszbanasiak** [comment]
@chris-h1 if this is still valid feel free to reopen issue
