### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'popitem' with some yahoo symbols: ^SSMI, PE&OLES.MX, SDR.L

### ISSUE THREAD

**Issue by chris-h1** [lukaszbanasiak/yahoo-finance#63]
Some yahoo symbols can't be fetched:

```
>>> yahoo = Share('^SSMI')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'
```

```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> yahoo = Share('PE&OLES.MX')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'
```

```
yahoo = Share('SDR.L')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/chris/.local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'
```

**Comment by huangyunict** [comment]
I encounter the same problem. It looks like the query does not escape special characters for URL. For example, index **^DJI** should be escaped to **%5EDJI**.

**Comment by davidimprovz** [comment]
I am getting this err as well, but only on a stock symbol, ENIA$. `Error trying to get ENIA$ info: 'NoneType' object has no attribute 'popitem'`

That symbol comes from the NASDAQ's CSV list downloaded from their site. As it only represents one stock out of the 6239 available (as of today) on both the NYSE and NASDAQ, I'm not going to worry about it. I've simply written a try / except to flag the symbol and avoid further updates. Using a pandas data frame, I loop over all the stocks available and do the following: 

```
yahoo_stock_elements, un_updatable = [], []
for idx, i in enumerate(all_exchanges.loc[:,'Symbol']):
    try: yahoo_stock_elements.append(yf(i))
    except Exception as e: un_updatable.append(i)
```

Of course, this solution also works for when the network can't be reached, [Errno 101]. Just track that stock and update it at a later time.
