### ISSUE TITLE
get_historical method produces null set

### ISSUE THREAD

**Issue by spjoynt** [lukaszbanasiak/yahoo-finance#67]
I'm trying to run the below statement and I keep getting a null set being printed. 
`print yahoo.get_historical('2014-04-25', '2014-04-29')` 

All the other methods work great!!

**Comment by jakubLangr** [comment]
Can confirm. 

Sometimes I also get this error:
```
Share('JPM').get_historical('2014-04-25', '2014-04-29')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/local/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
```

**Comment by lukaszbanasiak** [comment]
YQLQueryError is subclass of YQL* exceptions that means Yahoo endpoint respond with error. Details from Yahoo you have here `No definition found for Table yahoo.finance.quotes` @jakubLangr

**Comment by jakubLangr** [comment]
Yes I know, but the stock symbol is valid and worked before and is working now.
But I guess it is just a problem on the Yahoo side.
 





On Tue, Oct 4, 2016 11:32 AM, Łukasz Banasiak notifications@github.com
wrote:
YQLQueryError is subclass of YQL* exceptions that means Yahoo endpoint respond
with error. Details from Yahoo you have here No definition found for Table
yahoo.finance.quotes  @jakubLangr

**Comment by jwallden** [comment]
Works for me now.
