### ISSUE TITLE
Random JSON error

### ISSUE THREAD

**Issue by HenryJia** [lukaszbanasiak/yahoo-finance#68]
Hey

I've some code which loops through some Yahoo tickers and fetches today's OHLCV

It seems to randomly stop and give me this:

Traceback (most recent call last):
  File "fetch.py", line 79, in <module>
    data = fetch_since(s_clean, date_start)
  File "fetch.py", line 53, in fetch_since
    equity = yahoo_finance.Share(symbol)
  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 178, in __init__
  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 142, in refresh
  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 181, in _fetch
  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 134, in _fetch
  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 118, in _request
  File "build/bdist.linux-x86_64/egg/yahoo_finance/yql.py", line 62, in execute
  File "/home/henry/.local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/henry/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/henry/.local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jwallden** [comment]
Hi!
I get the same thing. A little print() in decoder.py (in the simplejson module) shows that sometimes Yahoo returns a webpage with an 504 timeout error message. This causes simplejson to throw this error.
This is an exerpt from the html returned:
`




`
Does anyone have any idea on how to prevent Yahoo from timing out? Is it a thing to prevent several successive calls to the api in a limited time? If that is the case we should consider implementing getting data for several stocks in batch. I saw yahoo-finance nodejs module doing this (this module however has its problems of its own by returning data for dates other than what was asked for...)

**Comment by lukaszbanasiak** [comment]
@jwallden so we need send batch request as one or something like keeping alive for connection?

**Comment by siam28** [comment]
There is already a pull request for doing a multi stock pull. Keeping the connection alive is also a good idea.

**Comment by jwallden** [comment]
Lukasz should have a look at that one then!
I actually think that keeping the connection alive or not doesn't matter. The problem lies in that Yahoo returns a timeout, not that we are closing the connection. Right?

**Comment by TheChymera** [comment]
I am getting the same error. It actually crashes more often than not, to the point that I could not test my scripts for the past half a day. Would be really great if we can solve this!

**Comment by TheChymera** [comment]
I get this error when trying to run the test suite from the current master HEAD:

```
 * python2_7: running distutils-r1_run_phase python_test
EEEEEEEEEE
======================================================================
ERROR: test_eurpln (__main__.TestCurrency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 90, in setUp
    self.eur_pln = Currency('EURPLN')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_eurpln_date (__main__.TestCurrency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 90, in setUp
    self.eur_pln = Currency('EURPLN')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_edt_to_utc (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_edt_to_utc_issue15 (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_get_date_range (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_get_historical (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_get_historical_1d (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_get_historical_longer_than_1y (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_get_info (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_yhoo (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 15, in setUp
    self.yahoo = Share('YHOO')
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/var/tmp/portage/dev-python/yahoo-finance-9999/work/yahoo-finance-9999-python2_7/lib/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 10 tests in 4.396s

FAILED (errors=10)
```

**Comment by TheChymera** [comment]
However, the test suite runs a bit better on the 1.2.1 release (this is reproducible):

```
 * python2_7: running distutils-r1_run_phase python_test
.s...FF.E.
======================================================================
ERROR: test_get_info (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 24, in test_get_info
    self.assertEqual(info['start'], '1996-04-12')
KeyError: 'start'

======================================================================
FAIL: test_get_historical (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 40, in test_get_historical
    self.assertDictEqual(history[0], expected)
AssertionError: {'Volume': '28736000', 'Symbol': 'YHOO', 'Adj_Close': '35.830002', 'High': '35.8 [truncated]... != {'High': '35.89', 'Volume': '28736000', 'Low': '34.12', 'Date': '2014-04-29', 'C [truncated]...
- {'Adj_Close': '35.830002',
?                     ----

+ {'Adj_Close': '35.83',
-  'Close': '35.830002',
?                 ----

+  'Close': '35.83',
   'Date': '2014-04-29',
-  'High': '35.889999',
?               ----

+  'High': '35.89',
-  'Low': '34.119999',
?              ^^^^^

+  'Low': '34.12',
?              ^

-  'Open': '34.369999',
?               ^^^^^

+  'Open': '34.37',
?               ^

   'Symbol': 'YHOO',
   'Volume': '28736000'}

======================================================================
FAIL: test_get_historical_1d (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 63, in test_get_historical_1d
    self.assertDictEqual(history[0], expected)
AssertionError: {'Volume': '28736000', 'Symbol': 'YHOO', 'Adj_Close': '35.830002', 'High': '35.8 [truncated]... != {'High': '35.89', 'Volume': '28736000', 'Low': '34.12', 'Date': '2014-04-29', 'C [truncated]...
- {'Adj_Close': '35.830002',
?                     ----

+ {'Adj_Close': '35.83',
-  'Close': '35.830002',
?                 ----

+  'Close': '35.83',
   'Date': '2014-04-29',
-  'High': '35.889999',
?               ----

+  'High': '35.89',
-  'Low': '34.119999',
?              ^^^^^

+  'Low': '34.12',
?              ^

-  'Open': '34.369999',
?               ^^^^^

+  'Open': '34.37',
?               ^

   'Symbol': 'YHOO',
   'Volume': '28736000'}

----------------------------------------------------------------------
Ran 10 tests in 12.830s

FAILED (failures=2, errors=1, skipped=1)
```
