### ISSUE TITLE
 Share object 

### ISSUE THREAD

**Issue by habibbd** [lukaszbanasiak/yahoo-finance#72]
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > from yahoo_finance import Share
> > > yahoo=Share('YHOO')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "yahoo_finance/**init**.py", line 178, in **init**
> > >     self.refresh()
> > >   File "yahoo_finance/**init**.py", line 142, in refresh
> > >     self.data_set = self._fetch()
> > >   File "yahoo_finance/__init__.py", line 181, in _fetch
> > >     data = super(Share, self)._fetch()
> > >   File "yahoo_finance/__init__.py", line 134, in _fetch
> > >     data = self._request(query)
> > >   File "yahoo_finance/__init__.py", line 123, in _request
> > >     raise YQLQueryError(response['error']['description'])
> > > yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
> > > exit()

**Comment by tchellomello** [comment]
+1 hitting the same issue here too. 

```python
/home/mdemello/devel/home_projects/toca_automation/home_assistant/server/configuration/deps/yahoo_finance/__init__.py in _request(self, query)
    121         except (KeyError, StopIteration):
    122             try:
--> 123                 raise YQLQueryError(response['error']['description'])
    124             except KeyError:
    125                 raise YQLResponseMalformedError()

YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
```

however it seems to be an issue with Yahoo API with some sort of load balancer or bad server. If you try in a loop, are you to reproduce the same?
```python
In [9]: while True:
    try:
        rht = Share('RHT')
        print(rht.get_price())
        break
    except Exception as e:
        print(e)
   ...:         
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
'NoneType' object has no attribute 'popitem'
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
77.80
```

@habibbd  are you able to experience the same?

**Comment by habibbd** [comment]
Hi @tchellomello 
Thx for the help.

Experienced the same as you.

>>> while True:
	try:
		yahoo = Share('YHOO')
		print(yahoo.get_price())
		break
	except Exception as e :
		print(e)

		
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
Query failed with error: "'No definition found for Table yahoo.finance.quotes'".
43.22

**Comment by tchellomello** [comment]
It is working now. Issue #71 has been closed. 

Is it working for you @habibbd ?

**Comment by lukaszbanasiak** [comment]
Duplicated with #71
