### ISSUE TITLE
Creating Share object fails in `raw_decode`

### ISSUE THREAD

**Issue by pmatos** [lukaszbanasiak/yahoo-finance#73]
From nothing to error:

```
(5) $ virtualenv-3.5 env
Using base prefix '/usr'
New python executable in /home/pmatos/Projects/portman/env/bin/python3
Also creating executable in /home/pmatos/Projects/portman/env/bin/python
Installing setuptools, pip, wheel...source env/done.
(6) $ source env/bin/activate
(7) $ pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python3.5/site-packages
(8) $ pip install yahoo-finance
Collecting yahoo-finance
  Downloading yahoo-finance-1.2.2.tar.gz
Collecting pytz (from yahoo-finance)
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 1.1MB/s 
Collecting simplejson (from yahoo-finance)
  Downloading simplejson-3.8.2.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 2.1MB/s 
Building wheels for collected packages: yahoo-finance, simplejson
  Running setup.py bdist_wheel for yahoo-finance ... done
  Stored in directory: /home/pmatos/.cache/pip/wheels/13/f0/df/199720c081f02135af5d10df2f2820e57f0183792f42b10674
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /home/pmatos/.cache/pip/wheels/e4/32/71/60b361b0d05433eb9d1dd3d47619931c08cc4e387dc494ad3c
Successfully built yahoo-finance simplejson
Installing collected packages: pytz, simplejson, yahoo-finance
Successfully installed pytz-2016.7 simplejson-3.8.2 yahoo-finance-1.2.2
(9) $ python
Python 3.5.1 (default, Sep 19 2016, 10:16:17) 
[GCC 6.1.1 20160621 (Red Hat 6.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yahoo_finance import Share
>>> yahoo = Share('YHOO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/pmatos/Projects/portman/env/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by grantrules** [comment]
I fixed this by switching from HTTPConnection to HTTPSConnection in yql.py

**Comment by nafooesi** [comment]
I found the same remedy.  Just curious, why use the low level client instead of urllib that can handle both http/https as suggested by the doc: https://docs.python.org/2/library/httplib.html

**Comment by grantrules** [comment]
Good point, I updated my branch for urllib2

**Comment by lukaszbanasiak** [comment]
Thank you @pmatos for report issue and @nafooesi @grantrules for fix it.
Version 1.3.1 published to pip.

**Comment by pmatos** [comment]
@lukaszbanasiak perfect. Thanks.
