### ISSUE TITLE
get_quote JSONDecodeError

### ISSUE THREAD

**Issue by Rudd-O** [lukaszbanasiak/yahoo-finance#82]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ledgerhelpers/programs/updateprices.py", line 319, in _gather_inner
    denominated_in=denominated_in
  File "/usr/lib/python2.7/site-packages/ledgerhelpers/programs/updateprices.py", line 126, in get_quote
    commodity_is_currency_pair=True
  File "/usr/lib/python2.7/site-packages/ledgerhelpers/programs/updateprices.py", line 78, in get_quote
    s = yahoo_finance.Currency(pair)
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 151, in __init__
    self.refresh()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 154, in _fetch
    data = super(Currency, self)._fetch()
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/usr/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)
  File "/usr/lib/python2.7/site-packages/yahoo_finance/yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 501, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Rudd-O** [comment]
Data returned:

```
<!DOCTYPE html>
<html lang="en-us"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Yahoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <style>
html {
    height: 100%;
}
body {
    background: #fafafc url(https://s.yimg.com/nn/img/sad-panda-201402200631.png) 50% 50%;
    background-size: cover;
    height: 100%;
    text-align: center;
    font: 300 18px "helvetica neue", helvetica, verdana, tahoma, arial, sans-serif;
}
table {
    height: 100%;
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;
    border-spacing: 0;
    border: none;
}
h1 {
    font-size: 42px;
    font-weight: 400;
    color: #400090;
}
p {
    color: #1A1A1A;
}
#message-1 {
    font-weight: bold;
    margin: 0;
}
#message-2 {
    display: inline-block;
    *display: inline;
    zoom: 1;
    max-width: 17em;
    _width: 17em;
}
#spanishContent {
    display: none;
}
    </style>
<script>
  document.write('<img src="//geo.yahoo.com/b?s=1197757129&t='+new Date().getTime()+'&err_url='+encodeURIComponent(document.URL)+'&err=400&test='+encodeURIComponent('-')+'" width="0px" height="0px"/>');
</script>
</head>
<body>
<!-- status code : 400 -->
<!-- Bad Request: GET -->
<!-- host machine: a37.ue.bf1.yahoo.net -->
<!-- timestamp: 1478556691.000 -->
<!-- url: http://query.yahooapis.com/v1/public/yql?q=select+%2A+from+yahoo.finance.quotes+where+symbol+%3D+%22GOOG%22&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&format=json-->
<table>
<tbody><tr>
    <td>
    <div id="englishContent">
        <script type="text/javascript">
        if (window.location.hostname=='att.yahoo.com'){
            document.write('<img src="https://s1.yimg.com/rz/d/att_en-US_f_p_bestfit_2x.png" alt="AT&T">');
        }else{
            document.write('<img src="https://s.yimg.com/nn/img/yahoo-logo-201402200629.png" alt="Yahoo Logo">');
        }    
        </script> 
        <h1 style="margin-top:20px;">Will be right back...</h1>
        <p id="message-1">Thank you for your patience.</p>
        <p id="message-2">Our engineers are working quickly to resolve the issue.</p>
    </div>
    <div id="spanishContent"> 
        <img src="https://s1.yimg.com/rz/d/att_es-US_f_p_bestfit_2x.png" alt="AT&T En Vivo" style="max-width:310px">
        <h1 style="margin-top:20px;">Volvemos enseguida…</h1>
        <p id="message-1">Gracias por tu paciencia.</p>
        <p id="message-2">Nuestros ingenieros están trabajando rápidamente para resolver el problema.</p>
    </div>
    <script type="text/javascript">
    if (window.location.hostname=='espanol.att.yahoo.com'){
        document.getElementById('englishContent').style.display = 'none';
        document.getElementById('spanishContent').style.display = 'block';
    }   
    </script>
    </td>
</tr>
</tbody></table>


</body></html>
```
