### ISSUE TITLE
Yahoo Finance Api not working

### ISSUE THREAD

**Issue by vicky113** [lukaszbanasiak/yahoo-finance#84]
I am trying to run the below code and it's not giving me any outputs while all my other Python programs(which does not use Yahoo Finance Library) are working fine.

```
import yahoo_finance
from pylab import *
import numpy as np
import scipy.signal as sc
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

ticker = 'GLD'
begdate = '2014-11-11'
enddate = '2016-11-11'
data = yahoo_finance.Share('GLD')
data1 = data.get_historical(begdate,enddate)
gld_df = pd.DataFrame(data1)
date_df = pd.to_datetime((list(gld_df["Date"])))
adj_close_df = list(gld_df["Adj_Close"])
plt.plot(date_df,adj_close_df)
plt.title("SPDR Gold Shares ")

detrend = sc.detrend(adj_close_df)
plt.plot(date_df,detrend)
plt.title("SPDR Gold Detrend Prices")
```

This is the error I got finally. I am very new to Python, I am not sure what this means.

I am using Python3.x, Anaconda. The script was working fine yesterday.

```
Traceback (most recent call last):

  File "<ipython-input-3-6c3ded7287fd>", line 1, in <module>
    runfile('D:/Quant/MSQF/4 - Algorithms 1/3-Sorting/Mini Project 2.py', wdir='D:/Quant/MSQF/4 - Algorithms 1/3-Sorting')

  File "D:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Quant/MSQF/4 - Algorithms 1/3-Sorting/Mini Project 2.py", line 19, in <module>
    data = yahoo_finance.Share('GLD')

  File "D:\Anaconda\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
    self.refresh()

  File "D:\Anaconda\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
    self.data_set = self._fetch()

  File "D:\Anaconda\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()

  File "D:\Anaconda\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
    data = self._request(query)

  File "D:\Anaconda\lib\site-packages\yahoo_finance\__init__.py", line 118, in _request
    response = yql.YQLQuery().execute(query)

  File "D:\Anaconda\lib\site-packages\yahoo_finance\yql.py", line 60, in execute
    return simplejson.loads(self.connection.getresponse().read())

  File "D:\Anaconda\lib\http\client.py", line 1197, in getresponse
    response.begin()

  File "D:\Anaconda\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()

  File "D:\Anaconda\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"

RemoteDisconnected: Remote end closed connection without response

```

**Comment by postmanisonline** [comment]
Observing something similar here.
Code that worked in the early morning does not work anymore.
There seems to be no answer from yahoo anymore.

**Comment by vicky113** [comment]
I tried downloading stock data via Pandas from yahoo and that works fine. Not sure what happened here.

**Comment by postmanisonline** [comment]
Here everything works fine again ...

**Comment by sresam89** [comment]
Anyone Any luck on getting this code working?
