### ISSUE TITLE
An YQL that returns no results causes a YQLResponseMalformedError even with a valid response

### ISSUE THREAD

**Issue by gvenkatas** [lukaszbanasiak/yahoo-finance#90]
Query:
select * from yahoo.finance.historicaldata where symbol = "BNDX" and startDate="2012-06-03" and endDate="2013-06-03"

Response:
{'query': {'count': 0, 'lang': 'en-US', 'results': None, 'created': '2016-11-22T01:30:18Z'}}

It looks like this change caused it:
https://github.com/lukaszbanasiak/yahoo-finance/commit/db06364e769b0b907d579fb43434ad3365d0fd07

Removing the AttributeError in the except clause makes this issue go away.

**Comment by IvanThinking** [comment]
I am experiencing this issue as well... any plan to fix?

**Comment by TarangKhanna** [comment]
Same, when the start and end dates are close for the historical data method I get:
raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.
Problem starts from a gap of 3 days.

**Comment by nlejeune** [comment]
Same issue here...

**Comment by vl3** [comment]
Same issue here. I've tried several gaps and i'm always getting YQLResponseMalformedError

**Comment by a-heintz** [comment]
I have the same issue. It worked about a week ago, but it no longer works now.

**Comment by vl3** [comment]
I think that the issue is yahoo API not the client.

**Comment by yatresh** [comment]
I am also facing the issue when i ran the command , Request Help.
pprint(yahoo.get_historical('2017-05-11', '2017-05-12'))

Error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yagrawal/Python/Historical_data.py", line 13, in <module>
    pprint(yahoo.get_historical('2017-05-11', '2017-05-12'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

Process finished with exit code 1

**Comment by joeyjoeyjoeey** [comment]
I am getting this issue when querying for historical data. All of the other methods which return current data seem to be working (get_price, get_change, get_book_value...).

Also using the python pandas DataReader method isn't working either.

**Comment by iakovace** [comment]
Same problem here, getting YQLResponseMalformedError(). Tried multiple combinations of dates and stocks. Is it something from yahoo that should be fixed in the following days?

**Comment by KentChun33333** [comment]
+1, same problem : 
According to following [blog]( http://www.financial-hacker.com/)
It seems ..... ~'~

**Comment by ikelca** [comment]
same problem here

**Comment by sameeksha16gupta** [comment]
When will this be fixed?

**Comment by stahl085** [comment]
Same problem

**Comment by Yevgnen** [comment]
Any news?

**Comment by xiangyueche** [comment]
Same issue here. Hope it can be fixed.

**Comment by DennyWeinberg** [comment]
+1

**Comment by knair99** [comment]
Here's a workaround (grab the data directly from the history pages):

```
import urllib2
from BeautifulSoup import BeautifulSoup as bs

def get_historical_data(name, number_of_days):
	data = []
	url = "https://finance.yahoo.com/quote/" + name + "/history/"
	rows = bs(urllib2.urlopen(url).read()).findAll('table')[0].tbody.findAll('tr')

	for each_row in rows:
		divs = each_row.findAll('td')
		if divs[1].span.text  != 'Dividend': #Ignore this row in the table
			#I'm only interested in 'Open' price; For other values, play with divs[1 - 5]
			data.append({'Date': divs[0].span.text, 'Open': float(divs[1].span.text.replace(',',''))})

	return data[:number_of_days]

#Test
print get_historical_data('amzn', 15)
```

**Comment by libnine** [comment]
Having an issue as well:

`Traceback (most recent call last):
  File "newsletter.py", line 54, in <module>
    crude = Share('CL=F')
  File "/home/qorka/.local/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 178, in __init__
    self.refresh()
  File "/home/qorka/.local/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "/home/qorka/.local/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "/home/qorka/.local/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 134, in _fetch
    data = self._request(query)
  File "/home/qorka/.local/lib/python2.7/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

`

**Comment by 3rico** [comment]
Same with me i have just started experiencing this today :-( what is happening?

**Comment by wtkao** [comment]
2017/11/8  The following code works! (for Python3)

import urllib
from bs4 import BeautifulSoup as bs

def get_historical_data(name, number_of_days):
    data = []
    url = "https://finance.yahoo.com/quote/" + name + "/history/"
    rows = bs(urllib.request.urlopen(url).read()).findAll('table')[0].tbody.findAll('tr')

    for each_row in rows:
        divs = each_row.findAll('td')
        if divs[1].span.text  != 'Dividend': #Ignore this row in the table
            #I'm only interested in 'Open' price; For other values, play with divs[1 - 5]
            data.append({'Date': divs[0].span.text, 'Open': float(divs[1].span.text.replace(',',''))})

    return data[:number_of_days]

#Test
for i in get_historical_data('AAPL', 5):
    print (i)

**Comment by knair99** [comment]
@wtkao Good to know it still works; I wrote that months ago and they change the HTML sometimes. As a caution, you might want to use urllib2 instead.
