### ISSUE TITLE
How to get historical data for commodities index/futures.

### ISSUE THREAD

**Issue by codesagar** [lukaszbanasiak/yahoo-finance#95]
I am trying to retrieve Nymex Crude historical data.
http://finance.yahoo.com/quote/CLF17.NYM?p=CLF17.NYM

**While the get_price() and get_open() works perfectly, I am having trouble in getting the historical data.** (even for the current month - past week). I get malformed expression error. (on both python2 and python3)

`>>> crude_oil = Share("CLF17.NYM")
>>> 
>>> oil = Share("CLF17.NYM")
>>> print(oil.get_price())
52.22
>>> print(oil.get_open())
52.11

## Here goes the error part
**print (oil.get_historical('2016-12-11', '2016-12-22'))**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)
  File "/opt/conda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

`

**Comment by wgreene18** [comment]
I'd like to get historical data for commodities and currency. It doesn't appear that the method 'get_historical()' is available for Currency. Is it possible to get that added as a method? I know that the Yahoo API does provide historical Currency data.

**Comment by daljeetv** [comment]
+1 for adding get_historical_data() method on Currency object.
